[tool.ruff]
line-length = 79
target-version = "py311"

[tool.black]
line-length = 79

[tool.pycln]
all = true

[tool.isort]
profile = "black"
line_length = 72
multi_line_output = 3

[[tool.mypy.overrides]]
module = [
    "mongopersistence",
]
ignore_missing_imports = true
